<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <RootNamespace>WinSetupHelper</RootNamespace>
    <AssemblyName>WinSetupHelper</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.0</Version>
    <Product>Windows Setup Helper</Product>
    <Description>Công cụ hỗ trợ cài đặt nhanh ứng dụng sau khi cài Windows</Description>
    <Copyright>aiplus4m</Copyright>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="apps.json" LogicalName="WinSetupHelper.apps.json" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.Net" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

</Project>
